### PR TITLE
Conditionally add image/webp as displayable inline.

### LINKED ISSUE #51: WebP not opened inline in Fx65+
Now supported natively by Firefox so I guess `'image/webp'` needs (conditionally?) adding to `MIME_TYPES_IMAGES`.

### PR DESCRIPTION
**Pull request by KwanEsq**
Support shipped in Firefox 65.
Fixes #51. 

Not sure if this is the best way to do it, but certainly fixes the problem for me.

### CODE REVIEW

**Comment by KwanEsq** [comment]
Out of curiosity, what result does that snippet give you in 65+?  Because I did actually try that earlier (though without the dimension setting) when I was trying to figure out if it was sniff-able, but I seem to get PNG even in WebP supporting Firefoxen.

**Comment by Rob--W** [comment]
Oh it doesn't work because Firefox doesn't support webp for toDataURL yet - https://bugzilla.mozilla.org/show_bug.cgi?id=1505383

You will have to load a webp image, and use `img.onerror` / `img.onload` + check for `img.naturalWidth` to check whether webp images can be loaded. This check is asynchronous, and you certainly have to cache the result to avoid performing the check over and over again.

**Comment by KwanEsq** [comment]
Okay new version with checking via an ``, cribbed heavily from the PDF check code (which I need to file an issue against...)
Checking img.naturalWidth doesn't seem to gain anything?  I get the expected results while toggling the pref as is, what would that add?

Test image is from https://hg.mozilla.org/mozilla-central/file/476293c6700f/image/test/gtest/green.webp.

**Comment by Rob--W** [comment]
Thanks for the patch and providing the source of the test image!

**Comment by OrangeDog** [comment]
@Rob--W can you push a new version with this fix in please?

**Comment by lol768** [comment]
> @Rob--W can you push a new version with this fix in please?

This please, it's an annoying bug.

**Comment by est31** [comment]
Hmm usually @Rob--W is quick to respond to requests like this... I'll upload a new version soon.

**Comment by est31** [comment]
2.9 is released on AMO. Seee also https://github.com/Rob--W/open-in-browser/pull/59

**Comment by Rob--W** [comment]
Oops. I wanted to look into the PDF detection, but didn't get to that and forgot to publish an update with this fix. Thanks @est31 for publishing the update.

**Pull request merged**
