### PR TITLE
Fix automatic resizing of the dialog

### PR DESCRIPTION
**Pull request by yan12125**
As described in https://github.com/spasche/openinbrowser/issues/23#issuecomment-334268040

### CODE REVIEW

**Comment by Rob--W** [comment]
Thanks for this PR. Could you explain how this patch is supposed to fix the bug? In particular, I wonder whether it is possible for the bug to occur with a different configuration (e.g. different window manager, zoom factor, pixel density, etc.)

**Comment by yan12125** [comment]
I didn't dig into Firefox internals. Here's my guess: a 10x10 window is too small to even contain a title bar, so the "content area" (I'm not sure if this term is correct or not) of the dialog is not shown. On my machine, scripts in dialog.html are not executed until the content area is visible. For example, if I insert ```<script>console.log(new Date)</script>``` into dialog.html, the logged time is when I resize the dialog manually. If I make the content area visible at first, things are going well.

I'm not sure about other configurations. I can checkout it out on other machines.

**Comment by Rob--W** [comment]
Can you change it to width 300 and height 150?

The goal of starting with a small width and then resizing it is to allow dialog.js to expand the popup just enough to fit the content. If the width/height is too large, then the dialog would take too much space. 300x150 is still small enough and probably a safe value.

I am suggesting 300 as a width because it was set in https://bugzilla.mozilla.org/show_bug.cgi?id=951928 (335px as minimum on macOS, 300px elsewhere).
The height suggestion of 150 is based on opening a new Firefox window, showing the menu items (e.g. press <kbd>Alt</kbd>) and measuring the height of the window.

**Comment by yan12125** [comment]
Thanks for the suggestion. I use 335 instead of 300 as the original bug occurs on macOS.

BTW, I tested the original resolution on Arch Linux (xfwm4) and that works, so this is a mac-only issue.

**Comment by Rob--W** [comment]
Merged, thanks.

**Pull request closed without merging**
